apiVersion: v1
kind: Service
metadata:
  name: movement-classification-service
  labels:
    app: movement-classification
spec:
  type: NodePort
  selector:
    app: movement-classification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
