apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api-image:latest # <--- NOTE: replace 12345 with your cluster's actual registry port if different from default, or just use the image name without the domain if k3d is configured to handle it directly. Let's try `api-image:latest` first as it's typically configured to use the local images.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-dataset-storage
          # CRITICAL: This mountPath must match ASSET_DIR in api/main.py
          mountPath: /app/api/assets # <--- MUST BE /app/api/assets (with an 's')
      volumes:
      - name: model-dataset-storage
        persistentVolumeClaim:
          claimName: model-dataset-pvc