apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api

        image: merlijn123/mlops-movement-classification-ai:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
