apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api

        image: api-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-dataset-storage
          mountPath: /app/api/assets 
      volumes:
      - name: model-dataset-storage
        persistentVolumeClaim:
          claimName: model-dataset-pvc
