apiVersion: v1
kind: Service
metadata:
  name: model-server-service
  labels:
    app: model-server
spec:
  type: ClusterIP 
  selector:
    app: model-server
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080 