apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Cluster-internal port
      targetPort: 80    # Container port
  type: LoadBalancer