apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-dataset-pv
spec:
  capacity:
    storage: 5Gi # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # IMPORTANT: This path is on the k3d cluster's node (the Docker container).
    # You will copy your model/dataset files to this path on the k3d node.
    path: "/mnt/k3d/data/model-dataset"
    type: DirectoryOrCreate