apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-dataset-pv
spec:
  capacity:
    storage: 5Gi # we need a lot of space for the model and dataset (multiple gigabytes)
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # this is for local development; in production, use a proper storage class
    path: "/mnt/k3d/data/model-dataset"
    type: DirectoryOrCreate