name: Apply Kubernetes Deployments

on:
  push:
    branches:
      - main # maybe replace this with a deployment branch
    paths:
      - 'kubernetes/**.yaml' 

env:
  AKS_RESOURCE_GROUP: ${{ vars.AKS_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ vars.AKS_CLUSTER_NAME }}

jobs:
  deploy-to-kubernetes:
    strategy:
      fail-fast: false
      matrix:
        runner: [self-hosted, ubuntu-latest]
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_YOUR_REPO }} # must be set in the repo secrets

    - name: Set up Kubeconfig for AKS
      run: |
        echo "Fetching AKS credentials for cluster: ${{ env.AKS_CLUSTER_NAME }} in resource group: ${{ env.AKS_RESOURCE_GROUP }}"
        az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }} --overwrite-existing --admin
      env:
        KUBECONFIG: /home/runner/.kube/config 

    - name: Verify kubectl configuration
      run: |
        kubectl config view
        kubectl get nodes

    - name: Apply Model Server Kubernetes Deployment
      run: |
        kubectl apply -f ./kubernetes/model-server-deployment.yaml

    - name: Apply API Kubernetes Deployment
      run: |
        kubectl apply -f ./kubernetes/api-deployment.yaml
